=== jesse99/whisper/Whisper/Source/BackEnd/COM/Resources/XBosses.dtd
<?xml version = "1.0" encoding = "UTF-8"?>

<!ENTITY % BOOL 	"(true|false)"> 
<!ENTITY % PLATF0RM	"(mac | win | carbon | classic_mac | all)">
<!ENTITY % TARGET 	"(release | debug | profile | all)">

<!-- In Microsoft's COM Whisper interfaces are typically mixed into one C++ object
and QueryInterface merely returns a pointer to one of the base classes. Whisper uses
a different model: each interface is typically implemented in a different C++ class
and interfaces are aggregated into "boss" objects.

This file defines the XML syntax used to specify the contents of bosses. You can
declare three types of boss objects: 1) normally you'll use the Boss element which
lets you list the interfaces in the boss 2) you can also use the AddInBoss element 
which lets you add new interfaces and/or replace the implementations in an existing 
boss (this makes plugins much more powerful) 3) finally you can use the AbstractBoss 
element to declare a boss that cannot be instantiated. This is useful because bosses 
can inherit the interfaces in other bosses. By using abstract bosses you can declare 
a common set of interfaces in one place.

Inside any of the bosses there are two elements you can use: 1) the Interface
element allows you to declare an interface by specifying the interface and implementation
names 2) the Parent elements allows you to pull in all the interfaces in another boss
(usually an abstract boss). -->
      

<!-- ****************** elements ****************** -->
<!ELEMENT BossList 		((AbstractBoss | AddInBoss | Boss)*)>
<!ELEMENT AbstractBoss 	((Interface | Inherit)*)>		
<!ELEMENT AddInBoss 	((Interface | Inherit)*)>		
<!ELEMENT Boss 			((Interface | Inherit)*)>
		
<!ELEMENT Interface 	EMPTY>									<!-- interfaces replace existing interfaces unless the name starts with a '+' character -->
<!ELEMENT Inherit 		EMPTY>									<!-- adds in all the interfaces in the parent boss (note that the ordering of the Interface and Inherit elements is significant) -->
<!ELEMENT Group 		(Interface*)>


<!-- ****************** attributes ****************** -->
<!ATTLIST Boss 			name 	 	CDATA		#REQUIRED>		<!-- this is the boss name used in the XInterfacePtr ctor -->
<!ATTLIST Boss 			singleton	%BOOL; 		"false">		<!-- singleton bosses are created when their plugin loads and destroyed when the plugin unloads -->

<!ATTLIST AbstractBoss 	name 	 	CDATA		#REQUIRED>
<!ATTLIST AbstractBoss 	singleton	%BOOL; 		#FIXED "false">

<!ATTLIST AddInBoss 	name 	 	CDATA		#REQUIRED>
<!ATTLIST AddInBoss 	singleton	%BOOL; 		#FIXED "false">

<!ATTLIST Interface 	name 		CDATA 		#REQUIRED>		<!-- used (indirectly) by QueryInterface -->
<!ATTLIST Interface 	impl 		CDATA 		#REQUIRED>		<!-- specifies the factory to use when creating the interface, note that these names must be globally unique, also "none" may be used inside an AbstractBoss -->
<!ATTLIST Interface		platform	%PLATF0RM;	"all">
<!ATTLIST Interface		target		%TARGET;	"all">

<!ATTLIST Inherit 		name 		CDATA 		#REQUIRED>		<!-- parent boss name -->
<!ATTLIST Inherit		platform	%PLATF0RM;	"all">
<!ATTLIST Inherit		target		%TARGET;	"all">

=== jesse99/whisper/Whisper/Source/UI/Resources/XML/Bosses.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?><!DOCTYPE BossList SYSTEM "XBosses.dtd"><!-- This file includes sample boss layouts for all the UI objects. Youcan use these bosses as is or you can create your own bosses if you needto customize the bosses or if you're concerned about code bloat. --><BossList><!-- Extensions (these are just for reference: you'll never actually inherit from one of these bosses) -->	<AbstractBoss name = "MenuExtensions">						<Group>			<Interface name = "IMenuExtension" impl = "XAssertExtension" target = "debug"/>			<Interface name = "IMenuExtension" impl = "XIntenseExtension" target = "debug"/>			<Interface name = "IMenuExtension" impl = "XObjectHeapExtension" target = "debug"/>			<Interface name = "IMenuExtension" impl = "XTraceExtension" target = "debug"/>			<Interface name = "IMenuExtension" impl = "XUnitTestExtension" target = "debug"/>			<Interface name = "IMenuExtension" impl = "XControlExtension" target = "debug"/>			<Interface name = "IMenuExtension" impl = "XInputTargetExtension" target = "debug"/>			<Interface name = "IMenuExtension" impl = "MMacsbugExtension" target = "debug" platform = "mac"/>			<Interface name = "IMenuExtension" impl = "MZoneRangerExtension" target = "debug" platform = "mac"/>			<Interface name = "IMenuExtension" impl = "MSIOUXExtension" target = "debug" platform = "mac"/>			<Interface name = "IMenuExtension" impl = "MSystemInfoExtension" target = "debug" platform = "mac"/>			<Interface name = "IMenuExtension" impl = "WSystemInfoExtension" target = "debug" platform = "win"/>		</Group>	</AbstractBoss>	<AbstractBoss name = "MouseExtensions">						<Group>			<Interface name = "IClickExtension, IMenuCommandClickExtension" impl = "XMenuCommandClickExtension"/>			<Interface name = "IClickExtension, ICommandClickExtension" impl = "XCommandClickExtension"/>			<Interface name = "IClickExtension, ICallbackClickExtension" impl = "XCallbackClickExtension"/>		</Group>	</AbstractBoss>	<AbstractBoss name = "DrawExtensions">						<Group>			<Interface name = "IDrawExtension, IFillExtension"   impl = "XEraseExtension"/>			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XLineLeftExtension"/>			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XLineRightExtension"/>			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XLineTopExtension"/>			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XLineBottomExtension"/>			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XFrameExtension"/>			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XShadowedFrameExtension"/>		</Group>	</AbstractBoss><!-- Application -->	<Boss name = "Application" singleton = "true">			<!-- must have this name -->				<Interface name = "IApplication" impl = "XApplication"/>		<Interface name = "IEventDispatcher" impl = "MEventDispatcher" platform = "mac"/>		<Interface name = "IMenuHandler" impl = "XAppMenuHandler"/>		<Interface name = "IWindowMgr" impl = "WindowMgr"/>		<Interface name = "IHierarchy" impl = "XHierarchy"/>		<Interface name = "IFocus" impl = "Focus"/>				<!-- optional interfaces -->		<Interface name = "IStringTableLoader" impl = "XStringTableLoader"/>						<Interface name = "IMenuBar" impl = "MenuBar" platform = "mac"/>		<Interface name = "IInitMenuBar" impl = "XInitMenuBar" platform = "mac"/>		<Interface name = "IActiveMenuBar" impl = "XActiveMenuBar"/>		<Interface name = "IIdler" impl = "XIdler"/>						<Interface name = "ITimer" impl = "XTimer"/>		<Interface name = "ICommandQueue" impl = "XCommandQueue"/>		<Interface name = "IActiveUndoContext" impl = "XActiveUndoContext"/>		<Interface name = "IUndoContext" impl = "XUndoContext"/>		<Interface name = "IMenuExtensible" impl = "XMenuExtensible"/>		<Interface name = "IKeyExtensible" impl = "XKeyExtensible"/>	</Boss><!-- Persistence -->	<Boss name = "XML Persist" singleton = "true">			<!-- must have this name -->		<Interface name = "IPersistXML" impl = "XPersistXML"/>	</Boss><!-- Drag and Drop App Progress Window -->	<Boss name = "Progress Window">						<Interface name = "IWindow" impl = "Window"/>			<Interface name = "IDraw" impl = "DrawWindow"/>			<Interface name = "IGeometry" impl = "WindowGeometry"/>			<Interface name = "IHierarchy" impl = "XHierarchy"/>		<Interface name = "IFocus" impl = "XWindowFocus"/>		<Interface name = "IDropAppProgress" impl = "XDropAppProgress"/>	</Boss><!-- Window -->	<Boss name = "Window">						<Interface name = "IWindow" impl = "Window"/>			<Interface name = "IDraw" impl = "DrawWindow"/>			<Interface name = "IGeometry" impl = "WindowGeometry"/>			<Interface name = "IMenuHandler" impl = "XWindowMenuHandler"/>		<Interface name = "IHierarchy" impl = "XHierarchy"/>		<Interface name = "IFocus" impl = "XWindowFocus"/>				<!-- optional interfaces -->		<Interface name = "IKeyHandler" impl = "XWindowKeyHandler"/>						<!-- handles tabbing to next control -->		<Interface name = "IMouseHandler" impl = "MWindowMouseHandler" platform = "mac"/>	<!-- need this if the window has controls -->		<Interface name = "IMenuBar" impl = "MMenuBar" platform = "win"/>		<Interface name = "IInitMenuBar" impl = "XInitMenuBar" platform = "win"/>		<Interface name = "IUndoContext" impl = "XUndoContext"/>				<Interface name = "IHelpText, ISetHelpText" impl = "XDefaultHelpText"/>		<Interface name = "IShowHelp" impl = "MBalloonHelp" platform = "classic_mac"/>		<Interface name = "IMenuExtensible" impl = "XMenuExtensible"/>		<Interface name = "IMouseExtensible" impl = "XMouseExtensible"/>		<Interface name = "IKeyExtensible" impl = "XKeyExtensible"/>		<Interface name = "IDrawExtensible" impl = "XDrawExtensible"/>	</Boss><!-- Menus -->	<Boss name = "Menu">							<Interface name = "IMenu" impl = "Menu"/>		<!-- optional -->		<Interface name = "IXMLMenu" impl = "XXMLMenu"/>				</Boss>	<Boss name = "Context Menu">							<Interface name = "IContextMenu" impl = "ContextMenu"/>		<Interface name = "IMenu" impl = "Menu"/>		<!-- optional -->		<Interface name = "IXMLMenu" impl = "XXMLMenu"/>				</Boss><!-- Commands -->	<Boss name = "Deferred Menu Command">							<Interface name = "ICommand, IDeferredMenuCommand" impl = "XDeferredMenuCommand"/>	</Boss>	<Boss name = "Deferred Error Command">							<Interface name = "ICommand, IDeferredErrorCommand" impl = "XDeferredErrorCommand"/>	</Boss>	<Boss name = "Callback Command">							<Interface name = "ICommand, ICallbackCommand" impl = "XCallbackCommand"/>	</Boss><!-- Undo Actions -->	<Boss name = "Multiple Undo Action">							<Interface name = "IUndoAction, IMultipleUndoAction" impl = "XMultipleUndoAction"/>		<Interface name = "ICommand" impl = "XUndoCommand"/>	</Boss>	<Boss name = "Undo Callback Action">							<Interface name = "IUndoAction, IUndoCallbackAction" impl = "XMultipleUndoAction"/>		<Interface name = "ICommand" impl = "XUndoCallbackAction"/>	</Boss><!-- Abstract Controls -->	<AbstractBoss name = "Base Control">							<Interface name = "IControl" impl = "Control"/>			<Interface name = "IDraw" impl = "DrawControl"/>			<Interface name = "IGeometry" impl = "ControlGeometry"/>			<Interface name = "IHierarchy" impl = "XHierarchy"/>				<!-- optional interfaces -->		<Interface name = "IMouseHandler" impl = "XControlMouseHandler"/>		<Interface name = "IHelpText, ISetHelpText, ISetDisabledHelp" impl = "XControlHelp"/>		<Interface name = "IShowHelp" impl = "MBalloonHelp" platform = "classic_mac"/>		<Interface name = "IMouseExtensible" impl = "XMouseExtensible"/>		<Interface name = "IDrawExtensible" impl = "XDrawExtensible"/>	</AbstractBoss>	<AbstractBoss name = "Value Control">							<Inherit name = "Base Control"/>		<Interface name = "IValueControl" impl = "ValueControl"/>				<!-- optional interfaces -->		<Interface name = "IHelpText, ISetHelpText, ISetDisabledHelp, ISetCheckedHelp" impl = "XButtonHelp"/>	</AbstractBoss>	<AbstractBoss name = "Targetable Control">							<Inherit name = "Base Control"/>		<Interface name = "IFocus" impl = "ControlFocus"/>		<Interface name = "IKeyHandler" impl = "ControlKeyHandler"/>						<!-- optional interfaces -->		<Interface name = "IKeyExtensible" impl = "XKeyExtensible"/>	</AbstractBoss><!-- Concrete Controls -->	<Boss name = "Group Control">							<Inherit name = "Group Control"/>		<Interface name = "IGroupControl" impl = "GroupControl"/>	</Boss>	<Boss name = "Progress Bar">							<Inherit name = "Value Control"/>		<Interface name = "IProgressBar" impl = "ProgressBar"/>		<Interface name = "IValueControl" impl = "M16BitValueControl" platform = "classic_mac"/>	<!-- progress bar doesn't handle 32-bit values... -->		<Interface name = "IValueControl" impl = "WProgressValueControl" platform = "win"/>		</Boss>	<Boss name = "Push Button">							<Inherit name = "Base Control"/>		<Interface name = "IPushButton" impl = "PushButton"/>		<Interface name = "IText" impl = "ControlText"/>		<Interface name = "IMouseExtensible" impl = "XMouseExtensible"/>	</Boss>	<Boss name = "Root Control">							<Inherit name = "Base Control"/>		<Interface name = "IRootControl" impl = "RootControl"/>		<Interface name = "IGeometry" impl = "MRootGeometry" platform = "mac"/>			<Interface name = "IParentChangedSize, IBinding" impl = "XDefaultChangedSize" platform = "win"/>	</Boss>	<Boss name = "Static Text">							<Inherit name = "Base Control"/>		<Interface name = "IStaticText, IText" impl = "MStaticText" platform = "mac"/>		<Interface name = "IStaticText" impl = "WStaticText" platform = "win"/>		<Interface name = "IText" impl = "ControlText" platform = "win"/>	</Boss></BossList>

=== jesse99/whisper/Whisper/Examples/DocSkeleton/Resources/XML/Bosses.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?><!DOCTYPE BossList SYSTEM "XBosses.dtd" [	<!ENTITY AbstractBosses	SYSTEM "XAbstractBosses.xml">]><BossList>	&AbstractBosses;<!-- This file contains the layout for all the COM bosses used by DocSkeleton. --><!-- Application -->	<Boss name = "Application" singleton = "true">						<Inherit name = "Base Application"/>		<Inherit name = "Application Extras"/>				<Inherit name = "Document App"/>				<Inherit name = "Debug Extensions" platform = "mac" target = "debug"/>				<Interface name = "ITimer" impl = "XTimer"/>		<Interface name = "+IInstallMenuHandler" impl = "CAppMenuHandler"/>		<Interface name = "IInit" impl = "CAppInit"/>		<Interface name = "IInitMenuBar" impl = "CInitMenuBar" platform = "mac"/>	</Boss><!-- Commands -->	<Boss name = "Callback Command">							<Interface name = "ICommand" impl = "XCommand"/>		<Interface name = "ICommandHelper, ICallbackCommand" impl = "XCallbackCommand"/>	</Boss>	<Boss name = "Undo Callback Action">							<Inherit name = "Base Undoable Command"/>		<Interface name = "IUndoActionHelper, IUndoCallbackAction" impl = "XUndoCallbackAction"/>	</Boss>	<Boss name = "Deferred Error Command">							<Interface name = "ICommand" impl = "XCommand"/>		<Interface name = "ICommandHelper, IDeferredErrorCommand" impl = "XDeferredErrorCommand"/>	</Boss>	<Boss name = "Cut Action">							<Inherit name = "Base Cut Action"/>	</Boss>	<Boss name = "Copy Action">							<Inherit name = "Base Copy Action"/>	</Boss>	<Boss name = "Paste Action">							<Inherit name = "Base Paste Action"/>	</Boss>	<Boss name = "Clear Action">							<Inherit name = "Base Clear Action"/>	</Boss>	<Boss name = "Typing Action">							<Inherit name = "Base Typing Action"/>	</Boss>	<Boss name = "Delete Action">							<Inherit name = "Base Delete Action"/>	</Boss>	<Boss name = "Forward Delete Action">							<Inherit name = "Base Forward Delete Action"/>	</Boss> <!-- Controls -->		<Boss name = "Document Control">							<Inherit name = "Abstract Control"/>			<Interface name = "IUserControl" impl = "XUserControl"/>		<Interface name = "IParentChangedSize, IBinding" impl = "XDefaultChangedSize"/>		<Interface name = "IHelpText, ISetHelp" impl = "XDefaultHelp"/>		<Interface name = "IShowHelp" impl = "MBalloonHelp" platform = "classic_mac"/>		<Interface name = "IShowHelp" impl = "WHTMLHelp" platform = "win"/>		<Interface name = "IDrawHelper" impl = "CDrawDoc"/>			<Interface name = "IMouseDownHelper" impl = "CMouseHandler"/>			<Interface name = "IAdjustCursorHelper" impl = "CAdjustCursor"/>		</Boss>	<Boss name = "Push Button">							<Inherit name = "Base Push Button"/>		<Interface name = "IClickExtension, ICallbackClickExtension" impl = "XCallbackClickExtension"/>	</Boss>	<Boss name = "Root Control">							<Inherit name = "Base Root Control"/>	</Boss>	<Boss name = "Static Text">							<Inherit name = "Base Static Text"/>	</Boss>	<Boss name = "Int32 Text Box">							<Inherit name = "Base Int32 Text Box"/>		<Interface name = "IHelpText, ISetHelp" impl = "XDefaultHelp"/>		<Interface name = "IShowHelp" impl = "MBalloonHelp" platform = "classic_mac"/>		<Interface name = "IShowHelp" impl = "WHTMLHelp" platform = "win"/>	</Boss><!-- Dialogs -->		<Boss name = "Width Dialog">						<Inherit name = "Base Dialog Box"/>		<Interface name = "IDialog" impl = "CWidthDialog"/>	</Boss>	<Boss name = "Pose Dialog Box">						<Inherit name = "Base Pose Dialog Box"/>	</Boss><!-- Document -->		<Boss name = "Document">			<Inherit name = "Base Document"/>				<Interface name = "IPersistDoc" impl = "XPersistDoc"/>		<Interface name = "IDocInfo" impl = "CDocInfo"/>					<Interface name = "+IDocWriter" impl = "CXMLWriter"/>			<Interface name = "+IDocReader" impl = "CXMLReader"/>				<Interface name = "+IDocWriter" impl = "CBinaryWriter"/>			<Interface name = "+IDocReader" impl = "CBinaryReader"/>			</Boss><!-- Menus -->	<Boss name = "Menu">							<Interface name = "IMenu" impl = "XMenu"/>	</Boss>	<Boss name = "Context Menu">							<Interface name = "IContextMenu" impl = "XContextMenu"/>		<Interface name = "IMenu" impl = "XMenu"/>	</Boss><!-- Persistence -->		<Boss name = "XML Persist" singleton = "true">		<Interface name = "IReadXML" impl = "XReadXML"/>		<Interface name = "IWriteXML" impl = "XWriteXML"/>	</Boss><!-- Trackers -->	<Boss name = "Rubber Band Tracker">							<Interface name = "ITracker" impl = "XTracker"/>		<Interface name = "ITrackerHelper" impl = "XRubberBandTracker"/>	</Boss><!-- Windows -->		<Boss name = "MDI Frame Window">						<Inherit name = "Base MDI Frame Window" platform = "win"/>		<Inherit name = "Debug Extensions" platform = "win" target = "debug"/>				<Interface name = "IInitMenuBar" impl = "CInitMenuBar" platform = "win"/>	</Boss>	<Boss name = "Document Window">						<Inherit name = "Base Document Window"/>		<Interface name = "IDrawHelper" impl = "XNullDrawer"/>			<Interface name = "+IInstallMenuHandler" impl = "XWindowMenuHandler"/>		<Interface name = "+IInstallMenuHandler" impl = "CDocMenuHandler"/>					</Boss></BossList>

=== jesse99/whisper/Whisper/Source/UI/Resources/XML/XSampleBosses.xml
<?xml version = "1.0" encoding = "UTF-8" standalone = "no"?>
<!DOCTYPE BossList SYSTEM "XBosses.dtd" [
	<!ENTITY AbstractBosses	SYSTEM "XAbstractBosses.xml">
]>

<!-- This file includes sample boss layouts for all the UI objects. You
     can use these bosses as is or you can create your own bosses if you 
     need to customize the bosses or if you're concerned about code bloat. -->

<BossList>
	&AbstractBosses;

<!-- Extensions (these are just for reference: you'll never actually inherit from one of these bosses) -->
	<AbstractBoss name = "MouseExtensions">				
		<Group>
			<Interface name = "IClickExtension, IMenuCommandClickExtension" impl = "XMenuCommandClickExtension"/>
			<Interface name = "IClickExtension, ICommandClickExtension" impl = "XCommandClickExtension"/>
			<Interface name = "IClickExtension, ICallbackClickExtension" impl = "XCallbackClickExtension"/>
		</Group>
	</AbstractBoss>

	<AbstractBoss name = "DrawExtensions">				
		<Group>
			<Interface name = "IDrawExtension, IFillExtension"   impl = "XEraseExtension"/>
			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XLineLeftExtension"/>
			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XLineRightExtension"/>
			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XLineTopExtension"/>
			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XLineBottomExtension"/>
			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XFrameExtension"/>
			<Interface name = "IDrawExtension, IStrokeExtension" impl = "XShadowedFrameExtension"/>
		</Group>
	</AbstractBoss>

<!-- Application -->
	<Boss name = "Optional Application Interfaces">			
		<Interface name = "IStringTableLoader" impl = "XStringTableLoader"/>				
		<Interface name = "IMenuBar" impl = "MenuBar" platform = "mac"/>
		<Interface name = "IActiveMenuBar" impl = "XActiveMenuBar"/>
		<Interface name = "IIdler" impl = "XIdler"/>				
		<Interface name = "ITimer" impl = "XTimer"/>
		<Interface name = "IXMLMenu" impl = "XXMLMenu"/>			

		<Interface name = "ICommandQueue" impl = "XCommandQueue"/>

		<Interface name = "IActiveUndoContext" impl = "XActiveUndoContext"/>
		<Interface name = "IUndoContext" impl = "XUndoContext"/>

		<Interface name = "IMenuExtensible" impl = "XMenuExtensible"/>
		<Interface name = "IKeyExtensible" impl = "XKeyExtensible"/>
	</Boss>

	<Boss name = "Application" singleton = "true">			<!-- must have this name -->		
		<Inherit name = "Base Application"/>
		<Inherit name = "Optional Application Interfaces"/>
	</Boss>

<!-- Persistence -->
	<Boss name = "XML Persist" singleton = "true">			<!-- must have this name -->
		<Interface name = "IPersistXML" impl = "XPersistXML"/>
	</Boss>

<!-- Drag and Drop App Progress Window -->
	<Boss name = "Progress Window">				
		<Inherit name = "Base Window"/>
		<Interface name = "IDropAppProgress" impl = "XDropAppProgress"/>
	</Boss>

<!-- Window -->
	<Boss name = "Optional Window Interfaces">				
		<Interface name = "IKeyHandler" impl = "XWindowKeyHandler"/>						<!-- handles tabbing to next control -->
		<Interface name = "IMouseHandler" impl = "MWindowMouseHandler" platform = "mac"/>	<!-- need this if the window has controls -->
		<Interface name = "IMenuBar" impl = "MMenuBar" platform = "win"/>
		<Interface name = "IUndoContext" impl = "XUndoContext"/>
		
		<Interface name = "IHelpText, ISetHelp" impl = "XDefaultHelp"/>
		<Interface name = "IShowHelp" impl = "MBalloonHelp" platform = "classic_mac"/>

		<Interface name = "IMenuExtensible" impl = "XMenuExtensible"/>
		<Interface name = "IMouseExtensible" impl = "XMouseExtensible"/>
		<Interface name = "IKeyExtensible" impl = "XKeyExtensible"/>
		<Interface name = "IDrawExtensible" impl = "XDrawExtensible"/>
	</Boss>

	<Boss name = "Window">				
		<Inherit name = "Base Window"/>
		<Inherit name = "Optional Window Interfaces"/>
	</Boss>

<!-- Menus -->
	<Boss name = "Menu">					
		<Interface name = "IMenu" impl = "Menu"/>
	</Boss>

	<Boss name = "Context Menu">					
		<Interface name = "IContextMenu" impl = "ContextMenu"/>
		<Interface name = "IMenu" impl = "Menu"/>
	</Boss>

<!-- Commands -->
	<Boss name = "Deferred Menu Command">					
		<Interface name = "ICommand, IDeferredMenuCommand" impl = "XDeferredMenuCommand"/>
	</Boss>

	<Boss name = "Deferred Error Command">					
		<Interface name = "ICommand, IDeferredErrorCommand" impl = "XDeferredErrorCommand"/>
	</Boss>

	<Boss name = "Callback Command">					
		<Interface name = "ICommand, ICallbackCommand" impl = "XCallbackCommand"/>
	</Boss>

<!-- Undo Actions -->
	<Boss name = "Multiple Undo Action">					
		<Interface name = "IUndoAction, IMultipleUndoAction" impl = "XMultipleUndoAction"/>
		<Interface name = "ICommand" impl = "XUndoCommand"/>
	</Boss>

	<Boss name = "Undo Callback Action">					
		<Interface name = "IUndoAction, IUndoCallbackAction" impl = "XUndoCallbackAction"/>
		<Interface name = "ICommand" impl = "XUndoCommand"/>
	</Boss>

<!-- Controls -->
	<AbstractBoss name = "Optional Control Interfaces">							
		<Interface name = "IMouseHandler" impl = "XControlMouseHandler"/>
		<Interface name = "IHelpText, ISetHelp, ISetDisabledHelp" impl = "XControlHelp"/>
		<Interface name = "IShowHelp" impl = "MBalloonHelp" platform = "classic_mac"/>

		<Interface name = "IMouseExtensible" impl = "XMouseExtensible"/>
		<Interface name = "IDrawExtensible" impl = "XDrawExtensible"/>
	</AbstractBoss>

	<Boss name = "Group Control">					
		<Inherit name = "Base Group Control"/>
		<Inherit name = "Optional Control Interfaces"/>
	</Boss>

	<Boss name = "Progress Bar">					
		<Inherit name = "Base Progress Bar"/>
		<Inherit name = "Optional Control Interfaces"/>
	</Boss>

	<Boss name = "Push Button">					
		<Inherit name = "Base Push Button"/>
		<Inherit name = "Optional Control Interfaces"/>
		
		<!-- optional interfaces $$$ move this to checkbox and radio button once they're implemented $$$ -->
		<Interface name = "IHelpText, ISetHelp, ISetDisabledHelp, ISetCheckedHelp" impl = "XButtonHelp"/>
	</Boss>

	<Boss name = "Root Control">					
		<Inherit name = "Base Root Control"/>
		<Inherit name = "Optional Control Interfaces"/>
	</Boss>

	<Boss name = "Scroll Bar">					
		<Inherit name = "Base Scroll Bar"/>
		<Inherit name = "Optional Control Interfaces"/>
	</Boss>

	<AbstractBoss name = "Scrollable Control">					
		<Inherit name = "Base Scrollable Control"/>
		<Inherit name = "Optional Control Interfaces"/>
		
		<!-- optional interfaces -->
		<Interface name = "IKeyExtensible" impl = "XKeyExtensible"/>
	</AbstractBoss>

	<Boss name = "Scroller Control">					
		<Inherit name = "Base Scroller Control"/>
		<Inherit name = "Optional Control Interfaces"/>
	</Boss>

	<Boss name = "Static Text">					
		<Inherit name = "Base Static Text"/>
		<Inherit name = "Optional Control Interfaces"/>
	</Boss>
</BossList>
