=== jesse99/whisper/Whisper/Source/UI/Resources/DTDs/XStringTable.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- this file defines the attributes and elements used to build a string table used
     to localize strings for different languages/regions -->
      

<!-- ****************** elements ****************** -->
<!ELEMENT StringTable (Entry)*>
<!ELEMENT Entry (Original, Text*)>
<!ELEMENT Original (#PCDATA)>
<!ELEMENT Text (#PCDATA)>


<!-- ****************** attributes ****************** -->
<!ATTLIST StringTable date CDATA "">	<!-- optional attributes for human consumption -->
<!ATTLIST StringTable time CDATA "">

<!ATTLIST Entry file CDATA "">			<!-- also optional -->
<!ATTLIST Entry synthetic CDATA "">		<!-- if this is "true" the original string is considered to be assembled at runtime and StringTableBuilder won't remove the string from the xml file -->

<!ATTLIST Text language CDATA #REQUIRED>
<!ATTLIST Text region CDATA "">

=== jesse99/whisper/Extras/HyperMandella/Resources/XML/Strings.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE StringTable SYSTEM "XStringTable.dtd">

<StringTable date = "3/17/2001" time = "1:08 AM">
	<Entry file = "CAppMenuHandler.cpp">
		<Original>A 4D fractal renderer written using the Whisper framework. Jesse Jones (c) 2000</Original>
	</Entry>

	<Entry file = "CBailoutDialog.cpp">
		<Original>Change Bailout</Original>
	</Entry>

	<Entry file = "CPointLightDialog.cpp">
		<Original>Change Light</Original>
	</Entry>

	<Entry file = "MMain.cpp WMain.cpp">
		<Original>Couldn't initialize the application.</Original>
	</Entry>

	<Entry file = "CAppMenuHandler.cpp">
		<Original>HyperMandella 1.0</Original>
	</Entry>

	<Entry file = "MMain.cpp">
		<Original>HyperMandella Prefs</Original>
	</Entry>

	<Entry file = "CInitMenuBar.cpp">
		<Original>Palette</Original>
	</Entry>

	<Entry file = "WMain.cpp">
		<Original>SOFTWARE\\Whisper\\HyperMandella\\1.0</Original>
	</Entry>

	<Entry file = "CDocMenuHandler.cpp">
		<Original>Set Palette</Original>
	</Entry>

</StringTable>

=== jesse99/whisper/Whisper/Examples/StringTableBuilder/Resources/XML/Strings.xml
<?xml version="1.0" encoding="Mac-Roman" standalone="no"?>
<!DOCTYPE StringTable SYSTEM "XStringTable.dtd">

<StringTable date = "7/14/99" time = "11:54 PM">
	<Entry file = "App.cpp">
		<Original>The file '#1' is #2.</Original>
	</Entry>

	<Entry file = "App.cpp">
		<Original>The folder '#1' contains #2 files and #3.</Original>
	</Entry>

	<Entry file = "App.cpp">
		<Original>The selected items contain #1 files and #2.</Original>
	</Entry>

	<Entry file = "App.cpp">
		<Original>Drop a file on the app to count the number of bytes in the file. Drop a folder on the app to (recursively) count the number of bytes within the folder.</Original>
	</Entry>
 
	<Entry file = "MMain.cpp">
		<Original>the Thread Manager</Original>
	</Entry>

	<Entry file = "MMain.cpp">
		<Original>DropSkeleton Prefs</Original>
	</Entry>

	<Entry file = "MMain.cpp">
		<Original>Couldn't initialize the application.</Original>
	</Entry>

	<Entry file = "ProcessFiles.cpp">
		<Original>Processing: </Original>
	</Entry>

	<Entry file = "WMain.cpp">
		<Original>SOFTWARE\\Whisper\\DropSkeleton\\1.0</Original>
	</Entry>
</StringTable>

=== jesse99/whisper/Whisper/Examples/DocSkeleton/Resources/XML/Strings.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE StringTable SYSTEM "XStringTable.dtd">

<StringTable date = "2/7/01" time = "10:36 PM">
	<Entry file = "CAppMenuHandler.cpp">
		<Original>A skeleton for document oriented applications using the Whisper framework. Jesse Jones (c) 2000</Original>
	</Entry>

	<Entry file = "CMouseHandler.cpp">
		<Original>Add Rect</Original>
	</Entry>

	<Entry file = "CDocMenuHandler.cpp">
		<Original>Change Color</Original>
	</Entry>

	<Entry file = "CWidthDialog.cpp">
		<Original>Change Pen Width</Original>
	</Entry>

	<Entry file = "MMain.cpp WMain.cpp">
		<Original>Couldn't initialize the application.</Original>
	</Entry>

	<Entry file = "CAppMenuHandler.cpp">
		<Original>DocSkeleton 1.0</Original>
	</Entry>

	<Entry file = "MMain.cpp">
		<Original>DocSkeleton Prefs</Original>
	</Entry>

	<Entry file = "CDocMenuHandler.cpp">
		<Original>Pick a fill color</Original>
	</Entry>

	<Entry file = "WMain.cpp">
		<Original>SOFTWARE\\Whisper\\HyperMandella\\1.0</Original>
	</Entry>

</StringTable>
